---
abstract: 'Content-Type header informed by shared-mime-info'
author:
  - 'Dorian Taylor, C<< <dorian at cpan.org> >>'
  - 'Dorian Taylor <dorian@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  Apache::Test: 0
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-MimeInfo
no_index:
  directory:
    - inc
    - t
requires:
  File::MimeInfo: 0
  IO::Scalar: 0
  mod_perl2: 0
  perl: 5.10.0
resources:
  license: http://apache.org/licenses/LICENSE-2.0
version: 0.05
